use_frameworks!

platform :ios, '8.0'

target 'DRPopAnimationView_Example' do
  pod 'DRPopAnimationView', :path => '../'

  target 'DRPopAnimationView_Tests' do
    inherit! :search_paths

    
  end
end
